package com.integration.auth.common.util;

public enum TargetTypes {

	JWT_EXTRACT_CLAIMS, SAVE_SESSION, TERMINATE_SESSION, SESSION_TOKEN, REFRESH_TOKEN, CREATE_TOKEN, VALIDATE_TOKEN,
	JWT_PARSER, JWT_CREATION_ERROR, JWT_DECODE_ERROR, JWT_VALIDATION_ERROR, GENERIC, GENERIC_ERROR,
	GENERIC_AUTH_FILTER_ERROR, UNIQUE_ID_GENERATOR, ENTITY_MAPPING, INTEGRATION_AUTH_TARGET, INVALID_USERNAME,
	INVALID_PASSWORD, INVALID_TENANT_ID, INVALID_PA_SYSTEM, INVALID_NATIVE_SYSTEM, EMPTY_JWT_CLAIMS, USER_EXISTS,
	PASSWORD_ENCODING_ERROR, PASSWORD_MATCHING_ERROR, PASSWORD_HASHING_ERROR, SALT_KEY_ERROR, USER_AUTHENTICATION_ERROR,
	SAVE_AUTH_USER, RETRIEVE_AUTH_USER, RETRIEVE_SECRET_DETAILS, INVALID_CLIENT_ID_AND_SECRET, INVALID_INPUT_STATUS,
	CONFLICT_ACTIVATION_STATUS, INACTIVE_USER, NORMAL_LOGIN, SSO_LOGIN, INVALID_REQUEST_BODY, PASSWORD_JOURNEY_TYPE;

}
